<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/studio/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:parameter="http://www.bonitasoft.org/ns/studio/parameter" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xmlns:transitions="http://www.bonitasoft.org/ns/studio/process/decision/transitions" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision http://www.bonitasoft.org/ns/studio/process/decision/transitions http://www.bonitasoft.org/ns/studio/process#//decision/transitions">
  <process:MainProcess xmi:id="_0HS_MJFBEeKG6e8lVkI_5A" name="Travel Request - BPMN Model" author="wagner" bonitaVersion="7.9.3" bonitaModelVersion="7.9.0-002" configId="ACED000574000E372E392E302D303032372E392E33">
    <elements xmi:type="process:Pool" xmi:id="_0QYpwJFBEeKG6e8lVkI_5A" name="Travel Request">
      <elements xmi:type="process:Lane" xmi:id="_0VNfYJFBEeKG6e8lVkI_5A" name="Employee" actor="_0U6kcJFBEeKG6e8lVkI_5A">
        <elements xmi:type="process:StartEvent" xmi:id="_0WDM4JFBEeKG6e8lVkI_5A" name="Start" outgoing="_8CWD0JYbEeKXusKkdNVONQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0WDz8ZFBEeKG6e8lVkI_5A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0WDz8JFBEeKG6e8lVkI_5A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0WDz8pFBEeKG6e8lVkI_5A" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_YBVF8JYWEeKXusKkdNVONQ" name="Modify the travel request" outgoing="_ssVZoJe8EeK8ctCg4Xe20A" incoming="_WLMDsJYWEeKXusKkdNVONQ _CpgV0JxCEeKyV6XuTI2IsA" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QPowQfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QPowQvUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QPowQ_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QPowRfUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QPowRvUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVZdZlEemLcsp6cmM4Hg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOVZtZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVZ9ZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVadZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcBtZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVaNZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVatZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_e73PIJYWEeKXusKkdNVONQ" name="Travel advance under limit" outgoing="_WLMDsJYWEeKXusKkdNVONQ _s0XrAJxAEeKyV6XuTI2IsA" incoming="_8CWD0JYbEeKXusKkdNVONQ _ssVZoJe8EeK8ctCg4Xe20A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP1kpfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP1kpvUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP1kp_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_ifwDIJe3EeK8ctCg4Xe20A" name="Manager" actor="_2Jev0JYXEeKXusKkdNVONQ">
        <elements xmi:type="process:Task" xmi:id="_v4Q50JxAEeKyV6XuTI2IsA" name="Validate Travel Request" outgoing="_-SJ7EJxBEeKyV6XuTI2IsA" incoming="_s0XrAJxAEeKyV6XuTI2IsA" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QPowS_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QPowTPUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QPowTfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QPowT_UWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QPowUPUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVcNZlEemLcsp6cmM4Hg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOVcdZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVctZlEemLcsp6cmM4Hg" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVdNZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcB9ZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVc9ZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVddZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_IK3FkJxCEeKyV6XuTI2IsA" name="Travel Request Status" outgoing="_CpgV0JxCEeKyV6XuTI2IsA _OhIEEJxCEeKyV6XuTI2IsA _SpK3gJxCEeKyV6XuTI2IsA" incoming="_-SJ7EJxBEeKyV6XuTI2IsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP1kqfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP1kqvUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP1kq_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_OgtNUJxCEeKyV6XuTI2IsA" name="Notify employee of approval" outgoing="_aFTlAJxaEeKyV6XuTI2IsA" incoming="_OhIEEJxCEeKyV6XuTI2IsA" useCardinality="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP1k3PUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP1k3fUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP1k3vUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QP1k4vUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QP1k4_UWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiO8ftZlEemLcsp6cmM4Hg" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiO8f9ZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiO8gNZlEemLcsp6cmM4Hg" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_So1gUJxCEeKyV6XuTI2IsA" name="Notify employee of rejection" outgoing="_Yv-dsJxCEeKyV6XuTI2IsA" incoming="_SpK3gJxCEeKyV6XuTI2IsA" useCardinality="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP1k5fUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP1k5vUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP1k5_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QP2Lo_UWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QP2LpPUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiO8htZlEemLcsp6cmM4Hg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiO8h9ZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiO8iNZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_YvmqQJxCEeKyV6XuTI2IsA" name="Request Rejected" incoming="_Yv-dsJxCEeKyV6XuTI2IsA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP2zC_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP2zDPUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP2zDfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_pM8SgJxaEeKyV6XuTI2IsA" name="Book tickets and arrange travel advance" outgoing="_Krz-gPUaEeK1NPHlZ0kUMw" incoming="_aFTlAJxaEeKyV6XuTI2IsA" useCardinality="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP3ZyfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP3ZyvUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP3Zy_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QP3ZzvUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QP3Zz_UWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiPjgdZlEemLcsp6cmM4Hg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiPjgtZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiPjg9ZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_BosGYPYFEeKh2PABpXVLRg" name="Travel Planning" content="Travel Planning" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_QP3Z2vUWEeK1NPHlZ0kUMw" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_kHLloPUaEeK1NPHlZ0kUMw" text="The end of this process can link to the Travel Expense process for this business trip"/>
        <elements xmi:type="process:EndSignalEvent" xmi:id="_8O6UcPU3EeK1NPHlZ0kUMw" name="Expense process initiation " signalCode="abc" incoming="_Krz-gPUaEeK1NPHlZ0kUMw">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_QiPjh9ZlEemLcsp6cmM4Hg" source="_kHLloPUaEeK1NPHlZ0kUMw"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KrZu0fUaEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KrZu0PUaEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KrZu0vUaEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_QiL5TtZlEemLcsp6cmM4Hg">
        <targetForm xmi:type="expression:Expression" xmi:id="_QiUcBNZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_QiL5T9ZlEemLcsp6cmM4Hg">
        <targetForm xmi:type="expression:Expression" xmi:id="_QiUcDdZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WLMDsJYWEeKXusKkdNVONQ" name="No" target="_YBVF8JYWEeKXusKkdNVONQ" source="_e73PIJYWEeKXusKkdNVONQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aR1eEJYYEeKXusKkdNVONQ">
          <lines xmi:type="decision:DecisionTableLine" xmi:id="_aR1eEZYYEeKXusKkdNVONQ">
            <conditions xmi:type="expression:Expression" xmi:id="_QP4A0PUWEeK1NPHlZ0kUMw" name="travelAdvance > advanceLimit" content="travelAdvance > advanceLimit" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
              <referencedElements xmi:type="parameter:Parameter" xmi:id="_aR1eFZYYEeKXusKkdNVONQ" name="advanceLimit" value="" typeClassname="java.lang.Integer" description=""/>
              <referencedElements xmi:type="process:Data" xmi:id="_QiQKktZlEemLcsp6cmM4Hg" name="travelAdvance" dataType="_0HS_M5FBEeKG6e8lVkI_5A"/>
            </conditions>
            <action xmi:type="transitions:TakeTransitionAction" xmi:id="_aR1eFpYYEeKXusKkdNVONQ" takeTransition="true"/>
          </lines>
          <defaultAction xmi:type="transitions:TakeTransitionAction" xmi:id="_aR1eF5YYEeKXusKkdNVONQ"/>
        </decisionTable>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z3fUWEeK1NPHlZ0kUMw" name="false" content="false" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8CWD0JYbEeKXusKkdNVONQ" target="_e73PIJYWEeKXusKkdNVONQ" source="_0WDM4JFBEeKG6e8lVkI_5A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8CWq4JYbEeKXusKkdNVONQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z5PUWEeK1NPHlZ0kUMw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ssVZoJe8EeK8ctCg4Xe20A" target="_e73PIJYWEeKXusKkdNVONQ" source="_YBVF8JYWEeKXusKkdNVONQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ssWAsJe8EeK8ctCg4Xe20A"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z5_UWEeK1NPHlZ0kUMw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_s0XrAJxAEeKyV6XuTI2IsA" name="Yes" target="_v4Q50JxAEeKyV6XuTI2IsA" source="_e73PIJYWEeKXusKkdNVONQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_s0YSEJxAEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z6vUWEeK1NPHlZ0kUMw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-SJ7EJxBEeKyV6XuTI2IsA" target="_IK3FkJxCEeKyV6XuTI2IsA" source="_v4Q50JxAEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-SKiIJxBEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z7PUWEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CpgV0JxCEeKyV6XuTI2IsA" name="Modify " target="_YBVF8JYWEeKXusKkdNVONQ" source="_IK3FkJxCEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CpgV0ZxCEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z7_UWEeK1NPHlZ0kUMw" name="modifyRequest" content="status.equalsIgnoreCase(&quot;Modify Request&quot;);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OhIEEJxCEeKyV6XuTI2IsA" name="Approved" target="_OgtNUJxCEeKyV6XuTI2IsA" source="_IK3FkJxCEeKyV6XuTI2IsA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OhIEEZxCEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z9PUWEeK1NPHlZ0kUMw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SpK3gJxCEeKyV6XuTI2IsA" name="Rejected" target="_So1gUJxCEeKyV6XuTI2IsA" source="_IK3FkJxCEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SpK3gZxCEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z9_UWEeK1NPHlZ0kUMw" name="false" content="false" interpreter="GROOVY" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Yv-dsJxCEeKyV6XuTI2IsA" target="_YvmqQJxCEeKyV6XuTI2IsA" source="_So1gUJxCEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Yv_EwJxCEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z-_UWEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aFTlAJxaEeKyV6XuTI2IsA" target="_pM8SgJxaEeKyV6XuTI2IsA" source="_OgtNUJxCEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aFUMEJxaEeKyV6XuTI2IsA"/>
        <condition xmi:type="expression:Expression" xmi:id="_QP3Z_fUWEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Krz-gPUaEeK1NPHlZ0kUMw" target="_8O6UcPU3EeK1NPHlZ0kUMw" source="_pM8SgJxaEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Krz-gfUaEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Krz-gvUaEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_0U6kcJFBEeKG6e8lVkI_5A" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_2Jev0JYXEeKXusKkdNVONQ" name="Manager"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="__5Te8J3JEeKM_42wV3fuZw" name="Production" version="7.9.0-002" username="helen.kelly" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="__5TfAJ3JEeKM_42wV3fuZw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="__5TfAZ3JEeKM_42wV3fuZw" name="Employee actor">
            <groups xmi:type="actormapping:Groups" xmi:id="__5TfA53JEeKM_42wV3fuZw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="__5TfBZ3JEeKM_42wV3fuZw">
              <membership xmi:type="actormapping:MembershipType" xmi:id="__5TfBp3JEeKM_42wV3fuZw" group="/acme" role="member"/>
            </memberships>
            <roles xmi:type="actormapping:Roles" xmi:id="__5TfBJ3JEeKM_42wV3fuZw"/>
            <users xmi:type="actormapping:Users" xmi:id="__5TfAp3JEeKM_42wV3fuZw"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="__5TfB53JEeKM_42wV3fuZw" name="Manager">
            <groups xmi:type="actormapping:Groups" xmi:id="__5TfCZ3JEeKM_42wV3fuZw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="__5TfC53JEeKM_42wV3fuZw">
              <membership xmi:type="actormapping:MembershipType" xmi:id="__5TfDJ3JEeKM_42wV3fuZw" group="/acme" role="member"/>
            </memberships>
            <roles xmi:type="actormapping:Roles" xmi:id="__5TfCp3JEeKM_42wV3fuZw"/>
            <users xmi:type="actormapping:Users" xmi:id="__5TfCJ3JEeKM_42wV3fuZw"/>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5Te8Z3JEeKM_42wV3fuZw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5Te-J3JEeKM_42wV3fuZw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5Te_Z3JEeKM_42wV3fuZw" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5Te_p3JEeKM_42wV3fuZw" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5Te_53JEeKM_42wV3fuZw" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5UGCZ3JEeKM_42wV3fuZw" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5UGCp3JEeKM_42wV3fuZw" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5UGC53JEeKM_42wV3fuZw" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="__5UGDJ3JEeKM_42wV3fuZw" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A4vUWEeK1NPHlZ0kUMw" name="advanceLimit" value="1000" typeClassname="java.lang.Integer" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A4_UWEeK1NPHlZ0kUMw" name="mailHost" value="smtp.gmail.com" typeClassname="java.lang.String" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A5PUWEeK1NPHlZ0kUMw" name="mailPort" value="465" typeClassname="java.lang.Integer" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A5fUWEeK1NPHlZ0kUMw" name="mailFrom" value="Travel Desk&lt;bos.process.templates@gmail.com>" typeClassname="java.lang.String" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A5vUWEeK1NPHlZ0kUMw" name="mailUsername" value="bos.process.templates@gmail.com" typeClassname="java.lang.String" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A5_UWEeK1NPHlZ0kUMw" name="mailPassword" value="bosisawsome" typeClassname="java.lang.String" description=""/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="_pW6RsJYWEeKXusKkdNVONQ" name="advanceLimit" value="" typeClassname="java.lang.Integer" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="__Wim8JuWEeKUOtdWYebMeA" name="mailHost" value="" typeClassname="java.lang.String" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_IJ7vMJuXEeKUOtdWYebMeA" name="mailPort" value="" typeClassname="java.lang.Integer" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_JBg3cJuXEeKUOtdWYebMeA" name="mailFrom" value="" typeClassname="java.lang.String" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_JfzV8JuXEeKUOtdWYebMeA" name="mailUsername" value="" typeClassname="java.lang.String" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_K5vkYJuXEeKUOtdWYebMeA" name="mailPassword" value="" typeClassname="java.lang.String" description=""/>
      <contract xmi:type="process:Contract" xmi:id="_QiL5UNZlEemLcsp6cmM4Hg"/>
      <documents xmi:type="process:Document" xmi:id="_shP44Jx7EeKyV6XuTI2IsA" name="Document1">
        <mimeType xmi:type="expression:Expression" xmi:id="_QP4n7vUWEeK1NPHlZ0kUMw" name="application/octet-stream" content="application/octet-stream"/>
        <url xmi:type="expression:Expression" xmi:id="_QP4n7_UWEeK1NPHlZ0kUMw" content=""/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="_vieOMJx7EeKyV6XuTI2IsA" name="Document2">
        <mimeType xmi:type="expression:Expression" xmi:id="_QP4n8PUWEeK1NPHlZ0kUMw" name="application/octet-stream" content="application/octet-stream"/>
        <url xmi:type="expression:Expression" xmi:id="_QP4n8fUWEeK1NPHlZ0kUMw"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0RLT8JFBEeKG6e8lVkI_5A">
        <name xmi:type="expression:Expression" xmi:id="_QP4n9vUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4n9_UWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0RL7ApFBEeKG6e8lVkI_5A">
        <name xmi:type="expression:Expression" xmi:id="_QP4n-PUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4n-fUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0RL7BZFBEeKG6e8lVkI_5A">
        <name xmi:type="expression:Expression" xmi:id="_QP4n-vUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4n-_UWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0RL7CJFBEeKG6e8lVkI_5A">
        <name xmi:type="expression:Expression" xmi:id="_QP4n_PUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4n_fUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_0RL7C5FBEeKG6e8lVkI_5A">
        <name xmi:type="expression:Expression" xmi:id="_QP4n_vUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4n__UWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_gqM1YJxaEeKyV6XuTI2IsA" name="Travel Planning">
      <elements xmi:type="process:Lane" xmi:id="_loLyUJxaEeKyV6XuTI2IsA" name="Admin Team" actor="_bx_64JxbEeKyV6XuTI2IsA">
        <elements xmi:type="process:StartEvent" xmi:id="_rCiiMJxaEeKyV6XuTI2IsA" name="Start" outgoing="_tA2R0PUWEeK1NPHlZ0kUMw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rCrFEZxaEeKyV6XuTI2IsA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rCrFEJxaEeKyV6XuTI2IsA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rCrFEpxaEeKyV6XuTI2IsA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Cog4gJxcEeKyV6XuTI2IsA" name="Split Tasks" outgoing="_xqxDQPUWEeK1NPHlZ0kUMw _MLkPIPUcEeK1NPHlZ0kUMw" incoming="_tA2R0PUWEeK1NPHlZ0kUMw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QP4oC_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QP4oDPUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QP4oDfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IaQNoJxcEeKyV6XuTI2IsA" name="Provide ticket options to employee" outgoing="_fMzBMPUYEeK1NPHlZ0kUMw" incoming="_xqxDQPUWEeK1NPHlZ0kUMw _k2E94PUYEeK1NPHlZ0kUMw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QPowVvUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QPowV_UWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QPowWPUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:JavaObjectData" xmi:id="_PQ-UMJxkEeKyV6XuTI2IsA" name="user" transient="true" datasourceId="IN_MEMORY" dataType="_0HS_N5FBEeKG6e8lVkI_5A" className="org.bonitasoft.engine.identity.User">
            <defaultValue xmi:type="expression:Expression" xmi:id="_QP4oEvUWEeK1NPHlZ0kUMw" name="user" content="return apiAccessor.getIdentityAPI().getUser(employeeId);" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="org.bonitasoft.engine.identity.User">
              <referencedElements xmi:type="expression:Expression" xmi:id="_QP4oFfUWEeK1NPHlZ0kUMw" name="apiAccessor" content="apiAccessor" type="TYPE_ENGINE_CONSTANT" returnType="org.bonitasoft.engine.api.APIAccessor"/>
            </defaultValue>
          </data>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QPowW_UWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QPowXPUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVfNZlEemLcsp6cmM4Hg" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOVfdZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVftZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVgNZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcCNZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVf9ZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVgdZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_6hXloPUYEeK1NPHlZ0kUMw" name="Send ticket and hotel reservation to employee" outgoing="_1gpBQPUZEeK1NPHlZ0kUMw" incoming="_6hhWoPUYEeK1NPHlZ0kUMw" useCardinality="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6hYzwfUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6hYzwPUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6hYzwvUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6hYzxPUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6hYzxfUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiO8jtZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiO8j9ZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiO8kNZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_KTfsgPUXEeK1NPHlZ0kUMw" name="Arrange travel advance" outgoing="_OeZmsPUXEeK1NPHlZ0kUMw" incoming="_MLkPIPUcEeK1NPHlZ0kUMw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_77FcgfUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_77FcgPUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_77FcgvUWEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_77FchPUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_77FchfUWEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVh9ZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOViNZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVidZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVi9ZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcCdZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVitZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVjNZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_OeFdoPUXEeK1NPHlZ0kUMw" name="Notify employee to collect the advance" outgoing="_TfAZ0PUXEeK1NPHlZ0kUMw" incoming="_OeZmsPUXEeK1NPHlZ0kUMw" useCardinality="true">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OeK9MPUXEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OeKWIPUXEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OeK9MfUXEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OeK9M_UXEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OeK9NPUXEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiO8ltZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiO8l9ZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiO8mNZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_TeyXYPUXEeK1NPHlZ0kUMw" name="Travel Advance Complete" incoming="_TfAZ0PUXEeK1NPHlZ0kUMw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Tey-cfUXEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Tey-cPUXEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_TezlgPUXEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_1gi6oPUZEeK1NPHlZ0kUMw" name="Tickets and Hotel booked" incoming="_1gpBQPUZEeK1NPHlZ0kUMw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1gjhsfUZEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1gjhsPUZEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1gjhsvUZEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_FjuHsPU4EeK1NPHlZ0kUMw" name="Book the tickets" outgoing="_3XTdYPUYEeK1NPHlZ0kUMw" incoming="_zUz4UPUYEeK1NPHlZ0kUMw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_zUpgQfUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_zUpgQPUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_zUpgQvUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_zUpgRPUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_zUqHUPUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVktZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOVk9ZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVlNZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVltZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcCtZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVldZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVl9ZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_F5otUPU4EeK1NPHlZ0kUMw" name="Book hotel" outgoing="_6hhWoPUYEeK1NPHlZ0kUMw" incoming="_3XTdYPUYEeK1NPHlZ0kUMw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_3XBJgfUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_3XBJgPUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_3XBJgvUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_3XBJhPUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_3XBJhfUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVndZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOVntZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVn9ZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVodZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcC9ZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVoNZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVotZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_3rkvIPUWEeK1NPHlZ0kUMw" name="Employee" actor="_bx_64JxbEeKyV6XuTI2IsA">
        <elements xmi:type="process:XORGateway" xmi:id="_kUWJ0PUYEeK1NPHlZ0kUMw" name="Need more options ?" outgoing="_k2E94PUYEeK1NPHlZ0kUMw _zUz4UPUYEeK1NPHlZ0kUMw" incoming="_jj3vIPUYEeK1NPHlZ0kUMw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jjsI8fUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jjsI8PUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jjsI8vUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_yIf2MPUYEeK1NPHlZ0kUMw" name="Select the best option" outgoing="_jj3vIPUYEeK1NPHlZ0kUMw" incoming="_fMzBMPUYEeK1NPHlZ0kUMw" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fMopIfUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fMopIPUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fMopIvUYEeK1NPHlZ0kUMw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_fMpQMfUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_fMpQMvUYEeK1NPHlZ0kUMw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QiOVqNZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QiOVqdZlEemLcsp6cmM4Hg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QiOVqtZlEemLcsp6cmM4Hg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QiOVrNZlEemLcsp6cmM4Hg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QiUcDNZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QiOVq9ZlEemLcsp6cmM4Hg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QiOVrdZlEemLcsp6cmM4Hg" name="3600000" content="3600000" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_QiL5bdZlEemLcsp6cmM4Hg">
        <targetForm xmi:type="expression:Expression" xmi:id="_QiUcBdZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_QiL5btZlEemLcsp6cmM4Hg">
        <targetForm xmi:type="expression:Expression" xmi:id="_QiUcDtZlEemLcsp6cmM4Hg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tA2R0PUWEeK1NPHlZ0kUMw" target="_Cog4gJxcEeKyV6XuTI2IsA" source="_rCiiMJxaEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tA2R0fUWEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_tA244PUWEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xqxDQPUWEeK1NPHlZ0kUMw" target="_IaQNoJxcEeKyV6XuTI2IsA" source="_Cog4gJxcEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xqxDQfUWEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_xqxDQvUWEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OeZmsPUXEeK1NPHlZ0kUMw" target="_OeFdoPUXEeK1NPHlZ0kUMw" source="_KTfsgPUXEeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OeZmsfUXEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_OeaNwPUXEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_TfAZ0PUXEeK1NPHlZ0kUMw" target="_TeyXYPUXEeK1NPHlZ0kUMw" source="_OeFdoPUXEeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_TfAZ0fUXEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_TfAZ0vUXEeK1NPHlZ0kUMw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fMzBMPUYEeK1NPHlZ0kUMw" target="_yIf2MPUYEeK1NPHlZ0kUMw" source="_IaQNoJxcEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fMzBMfUYEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_fMzoQPUYEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jj3vIPUYEeK1NPHlZ0kUMw" target="_kUWJ0PUYEeK1NPHlZ0kUMw" source="_yIf2MPUYEeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jj4WMPUYEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_jj4WMfUYEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k2E94PUYEeK1NPHlZ0kUMw" name="Yes" target="_IaQNoJxcEeKyV6XuTI2IsA" source="_kUWJ0PUYEeK1NPHlZ0kUMw" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k2Fk8PUYEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_k2Fk8fUYEeK1NPHlZ0kUMw" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_zUz4UPUYEeK1NPHlZ0kUMw" target="_FjuHsPU4EeK1NPHlZ0kUMw" source="_kUWJ0PUYEeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_zUz4UfUYEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_zUz4UvUYEeK1NPHlZ0kUMw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_3XTdYPUYEeK1NPHlZ0kUMw" target="_F5otUPU4EeK1NPHlZ0kUMw" source="_FjuHsPU4EeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_3XUEcPUYEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_3XUEcfUYEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6hhWoPUYEeK1NPHlZ0kUMw" target="_6hXloPUYEeK1NPHlZ0kUMw" source="_F5otUPU4EeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6hhWofUYEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_6hhWovUYEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1gpBQPUZEeK1NPHlZ0kUMw" target="_1gi6oPUZEeK1NPHlZ0kUMw" source="_6hXloPUYEeK1NPHlZ0kUMw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1gpoUPUZEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_1gpoUfUZEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_MLkPIPUcEeK1NPHlZ0kUMw" target="_KTfsgPUXEeK1NPHlZ0kUMw" source="_Cog4gJxcEeKyV6XuTI2IsA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_MLk2MPUcEeK1NPHlZ0kUMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_MLk2MfUcEeK1NPHlZ0kUMw" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_bx_64JxbEeKyV6XuTI2IsA" name="Admin" initiator="true"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_XtwyoJ3KEeKM_42wV3fuZw" name="Production" version="7.9.0-002" username="william.jobs" password="bpm">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_Xtwyqp3KEeKM_42wV3fuZw">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_Xtwyq53KEeKM_42wV3fuZw" name="Admin">
            <groups xmi:type="actormapping:Groups" xmi:id="_XtwyrZ3KEeKM_42wV3fuZw"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_Xtwyr53KEeKM_42wV3fuZw">
              <membership xmi:type="actormapping:MembershipType" xmi:id="_XtwysJ3KEeKM_42wV3fuZw" group="/acme/Administration" role="member"/>
            </memberships>
            <roles xmi:type="actormapping:Roles" xmi:id="_Xtwyrp3KEeKM_42wV3fuZw"/>
            <users xmi:type="actormapping:Users" xmi:id="_XtwyrJ3KEeKM_42wV3fuZw">
              <user>jan.fisher</user>
              <user>joseph.hovell</user>
              <user>marc.marseau</user>
            </users>
          </actorMapping>
        </actorMappings>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_XtwyoZ3KEeKM_42wV3fuZw" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_Xtwyop3KEeKM_42wV3fuZw" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_Xtwyp53KEeKM_42wV3fuZw" id="DATA_TYPES"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_XtwyqJ3KEeKM_42wV3fuZw" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_XtwyqZ3KEeKM_42wV3fuZw" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_Xtwyt53KEeKM_42wV3fuZw" id="DATA_TYPES"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_XtwyuJ3KEeKM_42wV3fuZw" id="GROOVY_SCRIPT"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_XtwyuZ3KEeKM_42wV3fuZw" id="VALIDATOR"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_Xtwyup3KEeKM_42wV3fuZw" id="OTHER"/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A8_UWEeK1NPHlZ0kUMw" name="mailHost" value="smtp.gmail.com" typeClassname="java.lang.String" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A9PUWEeK1NPHlZ0kUMw" name="mailPort" value="465" typeClassname="java.lang.Integer" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A9fUWEeK1NPHlZ0kUMw" name="mailUsername" value="bos.process.templates@gmail.com" typeClassname="java.lang.String" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A9vUWEeK1NPHlZ0kUMw" name="mailPassword" value="bosisawsome" typeClassname="java.lang.String" description=""/>
        <parameters xmi:type="parameter:Parameter" xmi:id="_QP4A9_UWEeK1NPHlZ0kUMw" name="mailFrom" value="Travel Desk&lt;bos.process.templates@gmail.com>" typeClassname="java.lang.String" description=""/>
      </configurations>
      <parameters xmi:type="parameter:Parameter" xmi:id="__XZ-AJxkEeKyV6XuTI2IsA" name="mailHost" value="" typeClassname="java.lang.String" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_AVIxkJxlEeKyV6XuTI2IsA" name="mailPort" value="" typeClassname="java.lang.Integer" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_A9MQEJxlEeKyV6XuTI2IsA" name="mailUsername" value="" typeClassname="java.lang.String" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_Bw1TgJxlEeKyV6XuTI2IsA" name="mailPassword" value="" typeClassname="java.lang.String" description=""/>
      <parameters xmi:type="parameter:Parameter" xmi:id="_CvGSkJxlEeKyV6XuTI2IsA" name="mailFrom" value="" typeClassname="java.lang.String" description=""/>
      <contract xmi:type="process:Contract" xmi:id="_QiL5b9ZlEemLcsp6cmM4Hg"/>
      <documents xmi:type="process:Document" xmi:id="_2mOykJyAEeKyV6XuTI2IsA" documentation="tickets" name="tickets">
        <mimeType xmi:type="expression:Expression" xmi:id="_QP4n8vUWEeK1NPHlZ0kUMw" name="application/octet-stream" content="application/octet-stream"/>
        <url xmi:type="expression:Expression" xmi:id="_QP4n8_UWEeK1NPHlZ0kUMw" content=""/>
      </documents>
      <documents xmi:type="process:Document" xmi:id="_2mregJyAEeKyV6XuTI2IsA" documentation="hotelReservation" name="hotelReservation">
        <mimeType xmi:type="expression:Expression" xmi:id="_QP4n9PUWEeK1NPHlZ0kUMw" name="application/octet-stream" content="application/octet-stream"/>
        <url xmi:type="expression:Expression" xmi:id="_QP4n9fUWEeK1NPHlZ0kUMw" content=""/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gqUxMJxaEeKyV6XuTI2IsA">
        <name xmi:type="expression:Expression" xmi:id="_QP4oAPUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4oAfUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gqUxM5xaEeKyV6XuTI2IsA">
        <name xmi:type="expression:Expression" xmi:id="_QP4oAvUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4oA_UWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gqUxNpxaEeKyV6XuTI2IsA">
        <name xmi:type="expression:Expression" xmi:id="_QP4oBPUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4oBfUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gqUxOZxaEeKyV6XuTI2IsA">
        <name xmi:type="expression:Expression" xmi:id="_QP4oBvUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4oB_UWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_gqUxPJxaEeKyV6XuTI2IsA">
        <name xmi:type="expression:Expression" xmi:id="_QP4oCPUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QP4oCfUWEeK1NPHlZ0kUMw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_WtUZ8N2dEemkUdL9n-jjnA" name="Cliente">
      <elements xmi:type="process:StartEvent" xmi:id="_fD1Y8N2dEemkUdL9n-jjnA" name="interesse em viajar" outgoing="_ibLvQN2dEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_fD2nEd2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_fD2nEN2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_fD2nEt2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Activity" xmi:id="_x1KxAN2dEemkUdL9n-jjnA" name="Decidir canal de comunicacao com a Ag de Viagem" outgoing="_0qdjIN2dEemkUdL9n-jjnA" incoming="_ibLvQN2dEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_iZvk0d2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_iZvk0N2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_iZvk0t2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_iZwL4N2dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_iZwL4d2dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iZwL4t2dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_iZwL5N2dEemkUdL9n-jjnA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_iZwL492dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_3otc8N2dEemkUdL9n-jjnA" name="Canal de comunicacao" outgoing="_4KTuIN2dEemkUdL9n-jjnA _XNOMkN2eEemkUdL9n-jjnA" incoming="_0qdjIN2dEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_0qXcgd2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_0qXcgN2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_0qXcgt2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_4JzX0N2dEemkUdL9n-jjnA" name="Enviar Email" outgoing="_AtbwUN2fEemkUdL9n-jjnA" incoming="_4KTuIN2dEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_4JzX0t2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_4JzX0d2dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_4JzX092dEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_4JzX1N2dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_4JzX1d2dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_4JzX1t2dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_4JzX2N2dEemkUdL9n-jjnA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_4JzX192dEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_a6RtIN2eEemkUdL9n-jjnA" name="Preencher formulário web" outgoing="_8WmS8N2eEemkUdL9n-jjnA" incoming="_XNOMkN2eEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_XNB_Ud2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_XNB_UN2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_XNB_Ut2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_XNB_U92eEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_XNB_VN2eEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XNB_Vd2eEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_XNB_V92eEemkUdL9n-jjnA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_XNB_Vt2eEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_a6SUOd2eEemkUdL9n-jjnA">
          <targetForm xmi:type="expression:Expression" xmi:id="_a6SUOt2eEemkUdL9n-jjnA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_a6SUON2eEemkUdL9n-jjnA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_a6SUO92eEemkUdL9n-jjnA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_7mZlEN2eEemkUdL9n-jjnA" name="End1" incoming="_EPx1sN2fEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_7maMId2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_7maMIN2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_7maMIt2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_9UjwAN2eEemkUdL9n-jjnA" name="Gateway1" outgoing="_EPx1sN2fEemkUdL9n-jjnA" incoming="_8WmS8N2eEemkUdL9n-jjnA _AtbwUN2fEemkUdL9n-jjnA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_8Whacd2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_8WhacN2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_8Whact2eEemkUdL9n-jjnA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:Data" xmi:id="_iFA1gN2eEemkUdL9n-jjnA" name="canalDeComunicacao" dataType="_0HS_NpFBEeKG6e8lVkI_5A">
        <defaultValue xmi:type="expression:Expression" xmi:id="_iFA1gd2eEemkUdL9n-jjnA" name="email" content="email"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_WyGMQN2dEemkUdL9n-jjnA">
        <targetForm xmi:type="expression:Expression" xmi:id="_WyGMQd2dEemkUdL9n-jjnA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_WyGMQt2dEemkUdL9n-jjnA">
        <targetForm xmi:type="expression:Expression" xmi:id="_WyGMQ92dEemkUdL9n-jjnA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ibLvQN2dEemkUdL9n-jjnA" target="_x1KxAN2dEemkUdL9n-jjnA" source="_fD1Y8N2dEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ibMWUN2dEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ibM9YN2dEemkUdL9n-jjnA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0qdjIN2dEemkUdL9n-jjnA" target="_3otc8N2dEemkUdL9n-jjnA" source="_x1KxAN2dEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0qdjId2dEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_0qdjIt2dEemkUdL9n-jjnA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4KTuIN2dEemkUdL9n-jjnA" name="email" target="_4JzX0N2dEemkUdL9n-jjnA" source="_3otc8N2dEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4KTuId2dEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_4KTuIt2dEemkUdL9n-jjnA" name="canalDeComunicacao == &quot;email&quot;" content="canalDeComunicacao == &quot;email&quot;" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_vw59wN2eEemkUdL9n-jjnA" name="canalDeComunicacao" dataType="_0HS_NpFBEeKG6e8lVkI_5A">
            <defaultValue xmi:type="expression:Expression" xmi:id="_vw59wd2eEemkUdL9n-jjnA" name="email" content="email"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XNOMkN2eEemkUdL9n-jjnA" name="form web" target="_a6RtIN2eEemkUdL9n-jjnA" source="_3otc8N2dEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XNOzoN2eEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_XNOzod2eEemkUdL9n-jjnA" name="canalDeComunicacao == &quot;form_web&quot;" content="canalDeComunicacao == &quot;form_web&quot;" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_tXdaIN2eEemkUdL9n-jjnA" name="canalDeComunicacao" dataType="_0HS_NpFBEeKG6e8lVkI_5A"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8WmS8N2eEemkUdL9n-jjnA" target="_9UjwAN2eEemkUdL9n-jjnA" source="_a6RtIN2eEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8WmS8d2eEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_8WmS8t2eEemkUdL9n-jjnA" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AtbwUN2fEemkUdL9n-jjnA" target="_9UjwAN2eEemkUdL9n-jjnA" source="_4JzX0N2dEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AtbwUd2fEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_AtbwUt2fEemkUdL9n-jjnA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_EPx1sN2fEemkUdL9n-jjnA" target="_7mZlEN2eEemkUdL9n-jjnA" source="_9UjwAN2eEemkUdL9n-jjnA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_EPycwN2fEemkUdL9n-jjnA"/>
        <condition xmi:type="expression:Expression" xmi:id="_EPycwd2fEemkUdL9n-jjnA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_WyGMRN2dEemkUdL9n-jjnA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WyEXEN2dEemkUdL9n-jjnA">
        <name xmi:type="expression:Expression" xmi:id="_WyEXEd2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WyEXEt2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WyEXE92dEemkUdL9n-jjnA">
        <name xmi:type="expression:Expression" xmi:id="_WyEXFN2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WyEXFd2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WyEXFt2dEemkUdL9n-jjnA">
        <name xmi:type="expression:Expression" xmi:id="_WyEXF92dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WyEXGN2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WyEXGd2dEemkUdL9n-jjnA">
        <name xmi:type="expression:Expression" xmi:id="_WyEXGt2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WyEXG92dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_WyEXHN2dEemkUdL9n-jjnA">
        <name xmi:type="expression:Expression" xmi:id="_WyEXHd2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_WyEXHt2dEemkUdL9n-jjnA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_0HS_MZFBEeKG6e8lVkI_5A" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_0HS_MpFBEeKG6e8lVkI_5A" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_0HS_M5FBEeKG6e8lVkI_5A" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_0HS_NJFBEeKG6e8lVkI_5A" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_0HS_NZFBEeKG6e8lVkI_5A" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_0HS_NpFBEeKG6e8lVkI_5A" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_0HS_N5FBEeKG6e8lVkI_5A" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_0HS_OJFBEeKG6e8lVkI_5A" name="XML"/>
    <datatypes xmi:type="process:EnumType" xmi:id="_YPvnUJYUEeKXusKkdNVONQ" name="Cities">
      <literals>Melbourne</literals>
      <literals>Bangalore</literals>
      <literals>London</literals>
      <literals>New York</literals>
      <literals>Athenes</literals>
      <literals>Sydney</literals>
      <literals>Paris</literals>
      <literals>Chicago</literals>
      <literals>Denver</literals>
      <literals>Hongkong</literals>
      <literals>Brest</literals>
      <literals>Lille</literals>
      <literals>Toulouse</literals>
      <literals>Istanbul</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_TOxyYJYVEeKXusKkdNVONQ" name="TransportOptions">
      <literals>Flight</literals>
      <literals>Train</literals>
      <literals>Flight/Train</literals>
    </datatypes>
    <datatypes xmi:type="process:EnumType" xmi:id="_kBjBgJfBEeK8ctCg4Xe20A" name="ApprovalStatus">
      <literals>Approved</literals>
      <literals>Rejected</literals>
      <literals>Modify Request</literals>
    </datatypes>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_QiL5MNZlEemLcsp6cmM4Hg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_0HTmQJFBEeKG6e8lVkI_5A" type="Process" element="_0HS_MJFBEeKG6e8lVkI_5A" name="MyDiagram1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_W2Jl0N2dEemkUdL9n-jjnA" type="2007" element="_WtUZ8N2dEemkUdL9n-jjnA">
      <children xmi:type="notation:DecorationNode" xmi:id="_W2KM4N2dEemkUdL9n-jjnA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_W2KM4d2dEemkUdL9n-jjnA" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_fEHs0N2dEemkUdL9n-jjnA" type="3002" element="_fD1Y8N2dEemkUdL9n-jjnA" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_fEIT4N2dEemkUdL9n-jjnA" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_fEIT4d2dEemkUdL9n-jjnA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fEHs0d2dEemkUdL9n-jjnA" x="93" y="106"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_x1L_IN2dEemkUdL9n-jjnA" type="3006" element="_x1KxAN2dEemkUdL9n-jjnA" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_x1L_It2dEemkUdL9n-jjnA" type="5006"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_x1L_Id2dEemkUdL9n-jjnA" x="199" y="70" width="174" height="87"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_3ourEt2dEemkUdL9n-jjnA" type="3008" element="_3otc8N2dEemkUdL9n-jjnA" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_3ovSIN2dEemkUdL9n-jjnA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_3ovSId2dEemkUdL9n-jjnA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3ourE92dEemkUdL9n-jjnA" x="470" y="96" width="43" height="43"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_4J0l8N2dEemkUdL9n-jjnA" type="3027" element="_4JzX0N2dEemkUdL9n-jjnA" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_4J0l8t2dEemkUdL9n-jjnA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4J0l8d2dEemkUdL9n-jjnA" x="620" y="20"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_a6S7QN2eEemkUdL9n-jjnA" type="3005" element="_a6RtIN2eEemkUdL9n-jjnA" fontName="Sans" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_a6S7Qt2eEemkUdL9n-jjnA" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_a6S7Qd2eEemkUdL9n-jjnA" x="610" y="88" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_7mbaQN2eEemkUdL9n-jjnA" type="3062" element="_7mZlEN2eEemkUdL9n-jjnA" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_7mcBUN2eEemkUdL9n-jjnA" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_7mcBUd2eEemkUdL9n-jjnA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7mbaQd2eEemkUdL9n-jjnA" x="930" y="98"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_9Uk-IN2eEemkUdL9n-jjnA" type="3008" element="_9UjwAN2eEemkUdL9n-jjnA" fontName="Sans">
          <children xmi:type="notation:DecorationNode" xmi:id="_9Uk-It2eEemkUdL9n-jjnA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_9UllMN2eEemkUdL9n-jjnA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9Uk-Id2eEemkUdL9n-jjnA" x="800" y="98" width="43" height="43"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_W2Jl0d2dEemkUdL9n-jjnA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_W2Jl0t2dEemkUdL9n-jjnA" fontName="Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_W2Jl092dEemkUdL9n-jjnA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_W2Kz8N2dEemkUdL9n-jjnA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_W2Jl1N2dEemkUdL9n-jjnA" width="1113" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_0UJIYJFBEeKG6e8lVkI_5A" type="2007" element="_0QYpwJFBEeKG6e8lVkI_5A">
      <children xmi:type="notation:DecorationNode" xmi:id="_0UKWgJFBEeKG6e8lVkI_5A" type="5008" element="_0QYpwJFBEeKG6e8lVkI_5A"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_0UKWgZFBEeKG6e8lVkI_5A" type="7001" element="_0QYpwJFBEeKG6e8lVkI_5A">
        <children xmi:type="notation:Node" xmi:id="_QP52JfUWEeK1NPHlZ0kUMw" type="3007" element="_0VNfYJFBEeKG6e8lVkI_5A">
          <children xmi:type="notation:DecorationNode" xmi:id="_0VP7o5FBEeKG6e8lVkI_5A" type="5007" element="_0VNfYJFBEeKG6e8lVkI_5A"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_0VQisJFBEeKG6e8lVkI_5A" type="7002" element="_0VNfYJFBEeKG6e8lVkI_5A">
            <children xmi:type="notation:Shape" xmi:id="_0WFpIJFBEeKG6e8lVkI_5A" type="3002" element="_0WDM4JFBEeKG6e8lVkI_5A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dEPUWEeK1NPHlZ0kUMw" type="5024" element="_0WDM4JFBEeKG6e8lVkI_5A">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0WFpI5FBEeKG6e8lVkI_5A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0WFpIZFBEeKG6e8lVkI_5A" x="43" y="81"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YBdo0JYWEeKXusKkdNVONQ" type="3005" element="_YBVF8JYWEeKXusKkdNVONQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dE_UWEeK1NPHlZ0kUMw" type="5005" element="_YBVF8JYWEeKXusKkdNVONQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YBdo0ZYWEeKXusKkdNVONQ" x="357" y="66" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_e75rYJYWEeKXusKkdNVONQ" type="3008" element="_e73PIJYWEeKXusKkdNVONQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dFfUWEeK1NPHlZ0kUMw" type="5026" element="_e73PIJYWEeKXusKkdNVONQ">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_e76ScZYWEeKXusKkdNVONQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e75rYZYWEeKXusKkdNVONQ" x="176" y="74" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_0VPUkZFBEeKG6e8lVkI_5A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_0VP7oJFBEeKG6e8lVkI_5A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_0VP7oZFBEeKG6e8lVkI_5A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_0VQisZFBEeKG6e8lVkI_5A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0VP7opFBEeKG6e8lVkI_5A" x="45" y="10" width="978" height="172"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_QP52LfUWEeK1NPHlZ0kUMw" type="3007" element="_ifwDIJe3EeK8ctCg4Xe20A">
          <children xmi:type="notation:DecorationNode" xmi:id="_if7pUJe3EeK8ctCg4Xe20A" type="5007" element="_ifwDIJe3EeK8ctCg4Xe20A"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_if7pUZe3EeK8ctCg4Xe20A" type="7002" element="_ifwDIJe3EeK8ctCg4Xe20A">
            <children xmi:type="notation:Shape" xmi:id="_v4WZZZxAEeKyV6XuTI2IsA" type="3005" element="_v4Q50JxAEeKyV6XuTI2IsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dGPUWEeK1NPHlZ0kUMw" type="5005" element="_v4Q50JxAEeKyV6XuTI2IsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_v4WZZpxAEeKyV6XuTI2IsA" x="165" y="49" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IK6I4JxCEeKyV6XuTI2IsA" type="3008" element="_IK3FkJxCEeKyV6XuTI2IsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dGvUWEeK1NPHlZ0kUMw" type="5026" element="_IK3FkJxCEeKyV6XuTI2IsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_IK6v8ZxCEeKyV6XuTI2IsA" y="6"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IK6I4ZxCEeKyV6XuTI2IsA" x="395" y="45" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Og9E8JxCEeKyV6XuTI2IsA" type="3027" element="_OgtNUJxCEeKyV6XuTI2IsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dHfUWEeK1NPHlZ0kUMw" type="5017" element="_OgtNUJxCEeKyV6XuTI2IsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Og9E8ZxCEeKyV6XuTI2IsA" x="528" y="42" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_So5xwJxCEeKyV6XuTI2IsA" type="3027" element="_So1gUJxCEeKyV6XuTI2IsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dH_UWEeK1NPHlZ0kUMw" type="5017" element="_So1gUJxCEeKyV6XuTI2IsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_So5xwZxCEeKyV6XuTI2IsA" x="367" y="151" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Yv160JxCEeKyV6XuTI2IsA" type="3062" element="_YvmqQJxCEeKyV6XuTI2IsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dIfUWEeK1NPHlZ0kUMw" type="5090" element="_YvmqQJxCEeKyV6XuTI2IsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Yv2h4ZxCEeKyV6XuTI2IsA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Yv160ZxCEeKyV6XuTI2IsA" x="412" y="227"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pM-HsJxaEeKyV6XuTI2IsA" type="3063" element="_pM8SgJxaEeKyV6XuTI2IsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dJ_UWEeK1NPHlZ0kUMw" type="5093" element="_pM8SgJxaEeKyV6XuTI2IsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pM-HsZxaEeKyV6XuTI2IsA" x="689" y="38" width="132" height="66"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_kHNa0PUaEeK1NPHlZ0kUMw" type="3015" element="_kHLloPUaEeK1NPHlZ0kUMw">
              <children xmi:type="notation:DecorationNode" xmi:id="_kHOB4PUaEeK1NPHlZ0kUMw" type="5010" element="_kHLloPUaEeK1NPHlZ0kUMw"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_kHNa0fUaEeK1NPHlZ0kUMw"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_kHNa0vUaEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_kHNa0_UaEeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kHNa1PUaEeK1NPHlZ0kUMw" x="771" y="170" width="176" height="58"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8O_M8PU3EeK1NPHlZ0kUMw" type="3020" element="_8O6UcPU3EeK1NPHlZ0kUMw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8O_0APU3EeK1NPHlZ0kUMw" type="5035" element="_8O6UcPU3EeK1NPHlZ0kUMw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8O_0AfU3EeK1NPHlZ0kUMw" x="54" y="-49"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8O_M8fU3EeK1NPHlZ0kUMw" x="870" y="57" width="30" height="30"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_if6bMZe3EeK8ctCg4Xe20A"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_if6bMpe3EeK8ctCg4Xe20A" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_if6bM5e3EeK8ctCg4Xe20A"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_if7pUpe3EeK8ctCg4Xe20A"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_if6bNJe3EeK8ctCg4Xe20A" x="45" y="237" width="1042" height="312"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_0UJIYZFBEeKG6e8lVkI_5A"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_0UJIYpFBEeKG6e8lVkI_5A" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_0UJIY5FBEeKG6e8lVkI_5A"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_0UKWgpFBEeKG6e8lVkI_5A"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0UJIZJFBEeKG6e8lVkI_5A" width="1080" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_gtey4JxaEeKyV6XuTI2IsA" type="2007" element="_gqM1YJxaEeKyV6XuTI2IsA">
      <children xmi:type="notation:DecorationNode" xmi:id="_gtey5ZxaEeKyV6XuTI2IsA" type="5008" element="_gqM1YJxaEeKyV6XuTI2IsA"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_gtey5pxaEeKyV6XuTI2IsA" type="7001" element="_gqM1YJxaEeKyV6XuTI2IsA">
        <children xmi:type="notation:Node" xmi:id="_QP52UfUWEeK1NPHlZ0kUMw" type="3007" element="_loLyUJxaEeKyV6XuTI2IsA">
          <children xmi:type="notation:DecorationNode" xmi:id="_loWKY5xaEeKyV6XuTI2IsA" type="5007" element="_loLyUJxaEeKyV6XuTI2IsA"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_loWKZJxaEeKyV6XuTI2IsA" type="7002" element="_loLyUJxaEeKyV6XuTI2IsA">
            <children xmi:type="notation:Shape" xmi:id="_rCthUJxaEeKyV6XuTI2IsA" type="3002" element="_rCiiMJxaEeKyV6XuTI2IsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP6dKfUWEeK1NPHlZ0kUMw" type="5024" element="_rCiiMJxaEeKyV6XuTI2IsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rCuvcZxaEeKyV6XuTI2IsA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rCthUZxaEeKyV6XuTI2IsA" x="72" y="130"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Coki4JxcEeKyV6XuTI2IsA" type="3009" element="_Cog4gJxcEeKyV6XuTI2IsA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP7EIPUWEeK1NPHlZ0kUMw" type="5020" element="_Cog4gJxcEeKyV6XuTI2IsA">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ColJ8JxcEeKyV6XuTI2IsA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Coki4ZxcEeKyV6XuTI2IsA" x="186" y="123"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IaXiaJxcEeKyV6XuTI2IsA" type="3005" element="_IaQNoJxcEeKyV6XuTI2IsA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QP7EI_UWEeK1NPHlZ0kUMw" type="5005" element="_IaQNoJxcEeKyV6XuTI2IsA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IaXiaZxcEeKyV6XuTI2IsA" x="284" y="142" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6haB4PUYEeK1NPHlZ0kUMw" type="3027" element="_6hXloPUYEeK1NPHlZ0kUMw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_6hao8PUYEeK1NPHlZ0kUMw" type="5017" element="_6hXloPUYEeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6haB4fUYEeK1NPHlZ0kUMw" x="794" y="141" width="124" height="62"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KTj98PUXEeK1NPHlZ0kUMw" type="3005" element="_KTfsgPUXEeK1NPHlZ0kUMw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KTklAPUXEeK1NPHlZ0kUMw" type="5005" element="_KTfsgPUXEeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KTj98fUXEeK1NPHlZ0kUMw" x="284" y="45" width="120" height="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OeP1sPUXEeK1NPHlZ0kUMw" type="3027" element="_OeFdoPUXEeK1NPHlZ0kUMw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OeRD0PUXEeK1NPHlZ0kUMw" type="5017" element="_OeFdoPUXEeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OeP1sfUXEeK1NPHlZ0kUMw" x="452" y="45" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Te0zoPUXEeK1NPHlZ0kUMw" type="3003" element="_TeyXYPUXEeK1NPHlZ0kUMw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Te1asfUXEeK1NPHlZ0kUMw" type="5025" element="_TeyXYPUXEeK1NPHlZ0kUMw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Te1asvUXEeK1NPHlZ0kUMw" x="28" y="21"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Te1asPUXEeK1NPHlZ0kUMw" x="610" y="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1gkIwPUZEeK1NPHlZ0kUMw" type="3003" element="_1gi6oPUZEeK1NPHlZ0kUMw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1gkv0PUZEeK1NPHlZ0kUMw" type="5025" element="_1gi6oPUZEeK1NPHlZ0kUMw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1gkv0fUZEeK1NPHlZ0kUMw" x="5" y="12"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1gkIwfUZEeK1NPHlZ0kUMw" x="965" y="157"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Fj1ccPU4EeK1NPHlZ0kUMw" type="3005" element="_FjuHsPU4EeK1NPHlZ0kUMw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Fj2DgPU4EeK1NPHlZ0kUMw" type="5005" element="_FjuHsPU4EeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Fj1ccfU4EeK1NPHlZ0kUMw" x="483" y="141" width="128" height="64"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F5sXsPU4EeK1NPHlZ0kUMw" type="3005" element="_F5otUPU4EeK1NPHlZ0kUMw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_F5s-wPU4EeK1NPHlZ0kUMw" type="5005" element="_F5otUPU4EeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F5sXsfU4EeK1NPHlZ0kUMw" x="642" y="139" width="130" height="65"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_loVjUZxaEeKyV6XuTI2IsA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_loWKYJxaEeKyV6XuTI2IsA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_loWKYZxaEeKyV6XuTI2IsA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_loWKZZxaEeKyV6XuTI2IsA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_loWKYpxaEeKyV6XuTI2IsA" x="45" y="10" width="1061" height="257"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_3rq1wPUWEeK1NPHlZ0kUMw" type="3007" element="_3rkvIPUWEeK1NPHlZ0kUMw">
          <children xmi:type="notation:DecorationNode" xmi:id="_3rrc0PUWEeK1NPHlZ0kUMw" type="5007" element="_3rkvIPUWEeK1NPHlZ0kUMw"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_3rrc0fUWEeK1NPHlZ0kUMw" type="7002" element="_3rkvIPUWEeK1NPHlZ0kUMw">
            <children xmi:type="notation:Shape" xmi:id="_kUZ0MPUYEeK1NPHlZ0kUMw" type="3008" element="_kUWJ0PUYEeK1NPHlZ0kUMw" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_kUabQPUYEeK1NPHlZ0kUMw" type="5026" element="_kUWJ0PUYEeK1NPHlZ0kUMw">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_kUabQfUYEeK1NPHlZ0kUMw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kUZ0MfUYEeK1NPHlZ0kUMw" x="441" y="38" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_yIjgkPUYEeK1NPHlZ0kUMw" type="3005" element="_yIf2MPUYEeK1NPHlZ0kUMw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_yIkHoPUYEeK1NPHlZ0kUMw" type="5005" element="_yIf2MPUYEeK1NPHlZ0kUMw"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_yIjgkfUYEeK1NPHlZ0kUMw" x="292" y="30" width="117" height="59"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_3rq1wfUWEeK1NPHlZ0kUMw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_3rq1wvUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_3rq1w_UWEeK1NPHlZ0kUMw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_3rrc0vUWEeK1NPHlZ0kUMw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3rq1xPUWEeK1NPHlZ0kUMw" x="45" y="512" width="978" height="143"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_gtey4ZxaEeKyV6XuTI2IsA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_gtey4pxaEeKyV6XuTI2IsA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_gtey45xaEeKyV6XuTI2IsA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_gtey55xaEeKyV6XuTI2IsA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gtey5JxaEeKyV6XuTI2IsA" width="1083" height="342"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_0HTmQZFBEeKG6e8lVkI_5A"/>
    <edges xmi:type="notation:Connector" xmi:id="_WLNR0JYWEeKXusKkdNVONQ" type="4001" element="_WLMDsJYWEeKXusKkdNVONQ" source="_e75rYJYWEeKXusKkdNVONQ" target="_YBdo0JYWEeKXusKkdNVONQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8SQPUWEeK1NPHlZ0kUMw" type="6001" element="_WLMDsJYWEeKXusKkdNVONQ">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SQfUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8SQvUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WLNR0pYWEeKXusKkdNVONQ" points="[22, 0, -169, -1]$[131, 0, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8CX5AJYbEeKXusKkdNVONQ" type="4001" element="_8CWD0JYbEeKXusKkdNVONQ" source="_0WFpIJFBEeKG6e8lVkI_5A" target="_e75rYJYWEeKXusKkdNVONQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8SRPUWEeK1NPHlZ0kUMw" type="6001" element="_8CWD0JYbEeKXusKkdNVONQ">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SRfUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8SRvUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8CX5ApYbEeKXusKkdNVONQ" points="[-1, -16, -138, -9]$[103, -16, -34, -9]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8Cd_oJYbEeKXusKkdNVONQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_8Cd_oZYbEeKXusKkdNVONQ" id="(0.7906976744186046,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ssX14Je8EeK8ctCg4Xe20A" type="4001" element="_ssVZoJe8EeK8ctCg4Xe20A" source="_YBdo0JYWEeKXusKkdNVONQ" target="_e75rYJYWEeKXusKkdNVONQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8SSvUWEeK1NPHlZ0kUMw" type="6001" element="_ssVZoJe8EeK8ctCg4Xe20A">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SS_UWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8STPUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ssX14pe8EeK8ctCg4Xe20A" points="[-61, -31, 219, -29]$[-61, -70, 219, -68]$[-280, -70, 0, -68]$[-280, -23, 0, -21]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ssd8gJe8EeK8ctCg4Xe20A" id="(1.0,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_s0auUJxAEeKyV6XuTI2IsA" type="4001" element="_s0XrAJxAEeKyV6XuTI2IsA" source="_e75rYJYWEeKXusKkdNVONQ" target="_v4WZZZxAEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8ST_UWEeK1NPHlZ0kUMw" type="6001" element="_s0XrAJxAEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SUPUWEeK1NPHlZ0kUMw" x="-8" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8SUfUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_s0auUpxAEeKyV6XuTI2IsA" points="[-2, 19, -30, -202]$[-2, 191, -30, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-SLJMJxBEeKyV6XuTI2IsA" type="4001" element="_-SJ7EJxBEeKyV6XuTI2IsA" source="_v4WZZZxAEeKyV6XuTI2IsA" target="_IK6I4JxCEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8SU_UWEeK1NPHlZ0kUMw" type="6001" element="_-SJ7EJxBEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SVPUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8SVfUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-SLJMpxBEeKyV6XuTI2IsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Cpg84JxCEeKyV6XuTI2IsA" type="4001" element="_CpgV0JxCEeKyV6XuTI2IsA" source="_IK6I4JxCEeKyV6XuTI2IsA" target="_YBdo0JYWEeKXusKkdNVONQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8SV_UWEeK1NPHlZ0kUMw" type="6001" element="_CpgV0JxCEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SWPUWEeK1NPHlZ0kUMw" x="19" y="3"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8SWfUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Cpg84pxCEeKyV6XuTI2IsA" points="[-24, -27, -3, 123]$[-24, -120, -3, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CpjZIJxCEeKyV6XuTI2IsA" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OhMVgJxCEeKyV6XuTI2IsA" type="4001" element="_OhIEEJxCEeKyV6XuTI2IsA" source="_IK6I4JxCEeKyV6XuTI2IsA" target="_Og9E8JxCEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP8SXPUWEeK1NPHlZ0kUMw" type="6001" element="_OhIEEJxCEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP8SXfUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP8SXvUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OhMVgpxCEeKyV6XuTI2IsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_SpPwAJxCEeKyV6XuTI2IsA" type="4001" element="_SpK3gJxCEeKyV6XuTI2IsA" source="_IK6I4JxCEeKyV6XuTI2IsA" target="_So5xwJxCEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP85UfUWEeK1NPHlZ0kUMw" type="6001" element="_SpK3gJxCEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP85UvUWEeK1NPHlZ0kUMw" x="8" y="-11"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP85U_UWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SpPwApxCEeKyV6XuTI2IsA" points="[0, 22, -11, -93]$[0, 85, -11, -30]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Yv_r0JxCEeKyV6XuTI2IsA" type="4001" element="_Yv-dsJxCEeKyV6XuTI2IsA" source="_So5xwJxCEeKyV6XuTI2IsA" target="_Yv160JxCEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP85VfUWEeK1NPHlZ0kUMw" type="6001" element="_Yv-dsJxCEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP85VvUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP85V_UWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Yv_r0pxCEeKyV6XuTI2IsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aFVaMJxaEeKyV6XuTI2IsA" type="4001" element="_aFTlAJxaEeKyV6XuTI2IsA" source="_Og9E8JxCEeKyV6XuTI2IsA" target="_pM-HsJxaEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QP85WfUWEeK1NPHlZ0kUMw" type="6001" element="_aFTlAJxaEeKyV6XuTI2IsA">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QP85WvUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QP85W_UWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aFVaMpxaEeKyV6XuTI2IsA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tA4uEPUWEeK1NPHlZ0kUMw" type="4001" element="_tA2R0PUWEeK1NPHlZ0kUMw" source="_rCthUJxaEeKyV6XuTI2IsA" target="_Coki4JxcEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tA5VIPUWEeK1NPHlZ0kUMw" type="6001" element="_tA2R0PUWEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tA5VIfUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tA4uEfUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tA4uEvUWEeK1NPHlZ0kUMw" points="[-17, -1, -1, -39]$[-22, 23, -6, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tBAp4PUWEeK1NPHlZ0kUMw" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xqzfgPUWEeK1NPHlZ0kUMw" type="4001" element="_xqxDQPUWEeK1NPHlZ0kUMw" source="_Coki4JxcEeKyV6XuTI2IsA" target="_IaXiaJxcEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xq0toPUWEeK1NPHlZ0kUMw" type="6001" element="_xqxDQPUWEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xq0tofUWEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xqzfgfUWEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xqzfgvUWEeK1NPHlZ0kUMw" points="[-22, 13, -126, 24]$[-22, 27, -126, 38]$[55, 27, -49, 38]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xq6NMPUWEeK1NPHlZ0kUMw" id="(1.0,0.6976744186046512)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xq6NMfUWEeK1NPHlZ0kUMw" id="(0.4083333333333333,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Oea00PUXEeK1NPHlZ0kUMw" type="4001" element="_OeZmsPUXEeK1NPHlZ0kUMw" source="_KTj98PUXEeK1NPHlZ0kUMw" target="_OeP1sPUXEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Oebb4PUXEeK1NPHlZ0kUMw" type="6001" element="_OeZmsPUXEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Oebb4fUXEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Oea00fUXEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Oea00vUXEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_TfBA4PUXEeK1NPHlZ0kUMw" type="4001" element="_TfAZ0PUXEeK1NPHlZ0kUMw" source="_OeP1sPUXEeK1NPHlZ0kUMw" target="_Te0zoPUXEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_TfBn8PUXEeK1NPHlZ0kUMw" type="6001" element="_TfAZ0PUXEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_TfBn8fUXEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_TfBA4fUXEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_TfBA4vUXEeK1NPHlZ0kUMw" points="[60, -1, -104, -6]$[150, -1, -14, -6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fM0PUPUYEeK1NPHlZ0kUMw" type="4001" element="_fMzBMPUYEeK1NPHlZ0kUMw" source="_IaXiaJxcEeKyV6XuTI2IsA" target="_yIjgkPUYEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fM02YPUYEeK1NPHlZ0kUMw" type="6001" element="_fMzBMPUYEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fM02YfUYEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fM0PUfUYEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fM0PUvUYEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jj6LYPUYEeK1NPHlZ0kUMw" type="4001" element="_jj3vIPUYEeK1NPHlZ0kUMw" source="_yIjgkPUYEeK1NPHlZ0kUMw" target="_kUZ0MPUYEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jj6ycPUYEeK1NPHlZ0kUMw" type="6001" element="_jj3vIPUYEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jj6ycfUYEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jj6LYfUYEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jj6LYvUYEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k2IBMPUYEeK1NPHlZ0kUMw" type="4001" element="_k2E94PUYEeK1NPHlZ0kUMw" source="_kUZ0MPUYEeK1NPHlZ0kUMw" target="_IaXiaJxcEeKyV6XuTI2IsA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k2IoQPUYEeK1NPHlZ0kUMw" type="6001" element="_k2E94PUYEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k2IoQfUYEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k2IBMfUYEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k2IBMvUYEeK1NPHlZ0kUMw" points="[-22, -30, 118, 123]$[-22, -165, 118, -12]$[-80, -165, 60, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_k2OH0PUYEeK1NPHlZ0kUMw" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_zVDv8PUYEeK1NPHlZ0kUMw" type="4001" element="_zUz4UPUYEeK1NPHlZ0kUMw" source="_kUZ0MPUYEeK1NPHlZ0kUMw" target="_Fj1ccPU4EeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_zVEXAPUYEeK1NPHlZ0kUMw" type="6001" element="_zUz4UPUYEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_zVEXAfUYEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_zVDv8fUYEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_zVDv8vUYEeK1NPHlZ0kUMw" points="[22, 0, -63, 143]$[87, 0, 2, 143]$[87, -111, 2, 32]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_3XWgsPUYEeK1NPHlZ0kUMw" type="4001" element="_3XTdYPUYEeK1NPHlZ0kUMw" source="_Fj1ccPU4EeK1NPHlZ0kUMw" target="_F5sXsPU4EeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_3XXHwPUYEeK1NPHlZ0kUMw" type="6001" element="_3XTdYPUYEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_3XXHwfUYEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_3XWgsfUYEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_3XWgsvUYEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6hikwPUYEeK1NPHlZ0kUMw" type="4001" element="_6hhWoPUYEeK1NPHlZ0kUMw" source="_F5sXsPU4EeK1NPHlZ0kUMw" target="_6haB4PUYEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6hikw_UYEeK1NPHlZ0kUMw" type="6001" element="_6hhWoPUYEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6hikxPUYEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6hikwfUYEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6hikwvUYEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1gqPYPUZEeK1NPHlZ0kUMw" type="4001" element="_1gpBQPUZEeK1NPHlZ0kUMw" source="_6haB4PUYEeK1NPHlZ0kUMw" target="_1gkIwPUZEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1gqPY_UZEeK1NPHlZ0kUMw" type="6001" element="_1gpBQPUZEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1gqPZPUZEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1gqPYfUZEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1gqPYvUZEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Kr0lkPUaEeK1NPHlZ0kUMw" type="4001" element="_Krz-gPUaEeK1NPHlZ0kUMw" source="_pM-HsJxaEeKyV6XuTI2IsA" target="_8O_M8PU3EeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Kr0lk_UaEeK1NPHlZ0kUMw" type="6001" element="_Krz-gPUaEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Kr0llPUaEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Kr0lkfUaEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Kr0lkvUaEeK1NPHlZ0kUMw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_MLmrYPUcEeK1NPHlZ0kUMw" type="4001" element="_MLkPIPUcEeK1NPHlZ0kUMw" source="_Coki4JxcEeKyV6XuTI2IsA" target="_KTj98PUXEeK1NPHlZ0kUMw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_MLnScPUcEeK1NPHlZ0kUMw" type="6001" element="_MLkPIPUcEeK1NPHlZ0kUMw">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_MLn5gPUcEeK1NPHlZ0kUMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_MLmrYfUcEeK1NPHlZ0kUMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_MLmrYvUcEeK1NPHlZ0kUMw" points="[-22, -28, -290, 49]$[-22, -77, -290, 0]$[208, -77, -60, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_MLsyAPUcEeK1NPHlZ0kUMw" id="(1.0,0.6511627906976745)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UDAv0N2dEemkUdL9n-jjnA" type="4003" element="_QiPjh9ZlEemLcsp6cmM4Hg" source="_kHNa0PUaEeK1NPHlZ0kUMw" target="_8O_M8PU3EeK1NPHlZ0kUMw">
      <styles xmi:type="notation:FontStyle" xmi:id="_UDAv0d2dEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UDAv0t2dEemkUdL9n-jjnA" points="[5, -29, -21, 98]$[23, -113, -3, 14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ibOykN2dEemkUdL9n-jjnA" type="4001" element="_ibLvQN2dEemkUdL9n-jjnA" source="_fEHs0N2dEemkUdL9n-jjnA" target="_x1L_IN2dEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ibQAsN2dEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ibQAsd2dEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ibOykd2dEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ibOykt2dEemkUdL9n-jjnA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0qeKMN2dEemkUdL9n-jjnA" type="4001" element="_0qdjIN2dEemkUdL9n-jjnA" source="_x1L_IN2dEemkUdL9n-jjnA" target="_3ourEt2dEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0qexQN2dEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0qexQd2dEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0qeKMd2dEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0qeKMt2dEemkUdL9n-jjnA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4KUVMN2dEemkUdL9n-jjnA" type="4001" element="_4KTuIN2dEemkUdL9n-jjnA" source="_3ourEt2dEemkUdL9n-jjnA" target="_4J0l8N2dEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4KUVM92dEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4KUVNN2dEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4KUVMd2dEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4KUVMt2dEemkUdL9n-jjnA" points="[0, -21, -183, 51]$[0, -73, -183, -1]$[133, -73, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XNaZ0N2eEemkUdL9n-jjnA" type="4001" element="_XNOMkN2eEemkUdL9n-jjnA" source="_3ourEt2dEemkUdL9n-jjnA" target="_a6S7QN2eEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XNaZ092eEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XNaZ1N2eEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XNaZ0d2eEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XNaZ0t2eEemkUdL9n-jjnA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8Wm6AN2eEemkUdL9n-jjnA" type="4001" element="_8WmS8N2eEemkUdL9n-jjnA" source="_a6S7QN2eEemkUdL9n-jjnA" target="_9Uk-IN2eEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8Wm6A92eEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8WnhEN2eEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8Wm6Ad2eEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8Wm6At2eEemkUdL9n-jjnA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AtcXYN2fEemkUdL9n-jjnA" type="4001" element="_AtbwUN2fEemkUdL9n-jjnA" source="_4J0l8N2dEemkUdL9n-jjnA" target="_9Uk-IN2eEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Atc-cN2fEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Atc-cd2fEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AtcXYd2fEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AtcXYt2fEemkUdL9n-jjnA" points="[0, 0, -97, -67]$[107, 0, 10, -67]$[107, 55, 10, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AteMkN2fEemkUdL9n-jjnA" id="(1.0,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EPzD0N2fEemkUdL9n-jjnA" type="4001" element="_EPx1sN2fEemkUdL9n-jjnA" source="_9Uk-IN2eEemkUdL9n-jjnA" target="_7mbaQN2eEemkUdL9n-jjnA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EPzq4N2fEemkUdL9n-jjnA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EPzq4d2fEemkUdL9n-jjnA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EPzD0d2fEemkUdL9n-jjnA" fontName="Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EPzD0t2fEemkUdL9n-jjnA" points="[-22, 8, -128, 50]$[111, -41, 5, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EP1gEN2fEemkUdL9n-jjnA" id="(1.0,0.7906976744186046)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_EP1gEd2fEemkUdL9n-jjnA" id="(0.7666666666666667,0.6)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
